[{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module '@/components/DesignCanvas' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 9,
	"startColumn": 98,
	"endLineNumber": 9,
	"endColumn": 125,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 's' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 101,
	"startColumn": 47,
	"endLineNumber": 101,
	"endColumn": 48,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 101,
	"startColumn": 50,
	"endLineNumber": 101,
	"endColumn": 51,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'i' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 101,
	"startColumn": 53,
	"endLineNumber": 101,
	"endColumn": 54,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 's' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 110,
	"startColumn": 39,
	"endLineNumber": 110,
	"endColumn": 40,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 110,
	"startColumn": 42,
	"endLineNumber": 110,
	"endColumn": 43,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'i' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 110,
	"startColumn": 45,
	"endLineNumber": 110,
	"endColumn": 46,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'wt' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 116,
	"startColumn": 42,
	"endLineNumber": 116,
	"endColumn": 44,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'e' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 266,
	"startColumn": 38,
	"endLineNumber": 266,
	"endColumn": 39,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'e' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 278,
	"startColumn": 52,
	"endLineNumber": 278,
	"endColumn": 53,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'e' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 564,
	"startColumn": 121,
	"endLineNumber": 564,
	"endColumn": 122,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 665,
	"startColumn": 42,
	"endLineNumber": 665,
	"endColumn": 43,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 665,
	"startColumn": 68,
	"endLineNumber": 665,
	"endColumn": 69,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 's' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 668,
	"startColumn": 57,
	"endLineNumber": 668,
	"endColumn": 58,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 668,
	"startColumn": 59,
	"endLineNumber": 668,
	"endColumn": 60,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'i' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 668,
	"startColumn": 61,
	"endLineNumber": 668,
	"endColumn": 62,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 's' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 773,
	"startColumn": 65,
	"endLineNumber": 773,
	"endColumn": 66,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 773,
	"startColumn": 67,
	"endLineNumber": 773,
	"endColumn": 68,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'i' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 773,
	"startColumn": 69,
	"endLineNumber": 773,
	"endColumn": 70,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 's' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 774,
	"startColumn": 57,
	"endLineNumber": 774,
	"endColumn": 58,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 774,
	"startColumn": 59,
	"endLineNumber": 774,
	"endColumn": 60,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'i' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 774,
	"startColumn": 61,
	"endLineNumber": 774,
	"endColumn": 62,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'wt' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 775,
	"startColumn": 75,
	"endLineNumber": 775,
	"endColumn": 77,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 's' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 779,
	"startColumn": 130,
	"endLineNumber": 779,
	"endColumn": 131,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'v' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 779,
	"startColumn": 132,
	"endLineNumber": 779,
	"endColumn": 133,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'i' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 779,
	"startColumn": 134,
	"endLineNumber": 779,
	"endColumn": 135,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'wt' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 779,
	"startColumn": 309,
	"endLineNumber": 779,
	"endColumn": 311,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'wt' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 796,
	"startColumn": 52,
	"endLineNumber": 796,
	"endColumn": 54,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'i' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 796,
	"startColumn": 56,
	"endLineNumber": 796,
	"endColumn": 57,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'el' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 809,
	"startColumn": 52,
	"endLineNumber": 809,
	"endColumn": 54,
	"modelVersionId": 25
},{
	"resource": "/c:/Users/lee_g/Downloads/enerus-plus-main/enerus-v2/app/jobs/[id]/design/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'e' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 821,
	"startColumn": 129,
	"endLineNumber": 821,
	"endColumn": 130,
	"modelVersionId": 25
}]